const String BOX_NAME_BOOK_LIST_VO = "BOX_NAME_BOOK_LIST_VO";
const String BOX_NAME_BOOK_VO = "BOX_NAME_BOOK_VO";
const String BOX_NAME_BUY_LINK_VO = "BOX_NAME_BUY_LINK_VO";
const String BOX_NAME_RESULT_VO = "BOX_NAME_RESULT_VO";
const String BOX_NAME_BOOK_DETAILS_VO = "BOX_NAME_BOOK_DETAILS_VO";
const String BOX_NAME_ISBNS_VO = "BOX_NAME_ISBNS_VO";
const String BOX_NAME_REVIEWS_VO = "BOX_NAME_REVIEWS_VO";
const String BOX_NAME_SHOW_MORE_LIST_FOR_HIVE_VO = "BOX_NAME_SHOW_MORE_LIST_FOR_HIVE_VO";
const String BOX_NAME_ACCESS_INFO_VO = "BOX_NAME_ACCESS_INFO_VO";
const String BOX_NAME_EPUB_VO = "BOX_NAME_EPUB_VO";
const String BOX_NAME_IMAGE_LINKS_VO = "BOX_NAME_IMAGE_LINKS_VO";
const String BOX_NAME_INDUSTRY_IDENTIFIER_VO = "BOX_NAME_INDUSTRY_IDENTIFIER_VO";
const String BOX_NAME_PANELIZATION_SUMMARY_VO = "BOX_NAME_PANELIZATION_SUMMARY_VO";
const String BOX_NAME_PDF_VO = "BOX_NAME_PDF_VO";
const String BOX_NAME_READING_MODES_VO = "BOX_NAME_READING_MODES_VO";
const String BOX_NAME_SALE_INFO_VO = "BOX_NAME_SALE_INFO_VO";
const String BOX_NAME_SEARCH_INFO_VO = "BOX_NAME_SEARCH_INFO_VO";
const String BOX_NAME_SEARCH_RESULT_VO = "BOX_NAME_SEARCH_RESULT_VO";
const String BOX_NAME_VOLUME_INFO_VO = "BOX_NAME_VOLUME_INFO_VO";

const String BOX_NAME_BOOK_LIST_FOR_CAROUSEL = "BOX_NAME_BOOK_LIST_FOR_CAROUSEL";
const String BOX_NAME_CHIP_VO = "BOX_NAME_CHIP_VO";
const String BOX_NAME_SHELF_VO = "BOX_NAME_SHELF_VO";

const int HIVE_TYPE_ID_BOOK_LIST_VO = 1;
const int HIVE_TYPE_ID_BOOK_VO = 2;
const int HIVE_TYPE_ID_BUY_LINK_VO = 3;
const int HIVE_TYPE_ID_RESULT_VO = 4;
const int HIVE_TYPE_ID_BOOK_DETAILS_VO = 5;
const int HIVE_TYPE_ID_ISBNS_VO = 6;
const int HIVE_TYPE_ID_REVIEWS_VO = 7;
const int HIVE_TYPE_ID_SHOW_MORE_LIST_FOR_HIVE_VO = 8;

const int HIVE_TYPE_ID_ACCESS_INFO_VO = 9;
const int HIVE_TYPE_ID_EPUB_VO = 10;
const int HIVE_TYPE_ID_IMAGE_LINKS_VO = 11;
const int HIVE_TYPE_ID_INDUSTRY_IDENTIFIER_VO = 12;
const int HIVE_TYPE_ID_PANELIZATION_SUMMARY_VO = 13;
const int HIVE_TYPE_ID_PDF_VO = 14;
const int HIVE_TYPE_ID_READING_MODES_VO = 15;
const int HIVE_TYPE_ID_SALE_INFO_VO = 16;
const int HIVE_TYPE_ID_SEARCH_INFO_VO = 17;
const int HIVE_TYPE_ID_SEARCH_RESULT_VO = 18;
const int HIVE_TYPE_ID_VOLUME_INFO_VO = 19;
const int HIVE_TYPE_ID_CHIP_VO = 20;
const int HIVE_TYPE_ID_SHELF_VO = 21;

