const String BOX_NAME_BOOK_LIST_VO = "BOX_NAME_BOOK_LIST_VO";
const String BOX_NAME_BOOK_VO = "BOX_NAME_BOOK_VO";
const String BOX_NAME_BUY_LINK_VO = "BOX_NAME_BUY_LINK_VO";
const String BOX_NAME_RESULT_VO = "BOX_NAME_RESULT_VO";
const String BOX_NAME_BOOK_DETAILS_VO = "BOX_NAME_BOOK_DETAILS_VO";
const String BOX_NAME_ISBNS_VO = "BOX_NAME_ISBNS_VO";
const String BOX_NAME_REVIEWS_VO = "BOX_NAME_REVIEWS_VO";
const String BOX_NAME_SHOW_MORE_RESULT_VO = "BOX_NAME_SHOW_MORE_RESULT_VO";

const int HIVE_TYPE_ID_BOOK_LIST_VO = 1;
const int HIVE_TYPE_ID_BOOK_VO = 2;
const int HIVE_TYPE_ID_BUY_LINK_VO = 3;
const int HIVE_TYPE_ID_RESULT_VO = 4;
const int HIVE_TYPE_ID_BOOK_DETAILS_VO = 5;
const int HIVE_TYPE_ID_ISBNS_VO = 6;
const int HIVE_TYPE_ID_REVIEWS_VO = 7;
const int HIVE_TYPE_ID_SHOW_MORE_RESULT_VO = 8;