import 'package:the_library_app/data/vos/google_search/access_info_vo.dart';
import 'package:the_library_app/data/vos/google_search/image_links_vo.dart';
import 'package:the_library_app/data/vos/google_search/panelization_summary_vo.dart';
import 'package:the_library_app/data/vos/google_search/reading_modes_vo.dart';
import 'package:the_library_app/data/vos/google_search/sale_info_vo.dart';
import 'package:the_library_app/data/vos/google_search/search_info_vo.dart';
import 'package:the_library_app/data/vos/google_search/search_result_vo.dart';
import 'package:the_library_app/data/vos/google_search/volume_info_vo.dart';
import 'package:the_library_app/data/vos/overview/book_list_vo.dart';
import 'package:the_library_app/data/vos/overview/book_vo.dart';
import 'package:the_library_app/data/vos/overview/result_vo.dart';
import 'package:the_library_app/data/vos/overview/show_more_list_for_hive_vo.dart';
import 'package:the_library_app/data/vos/shelf_vo.dart';
import 'package:the_library_app/data/vos/show_more/book_details_vo.dart';

ResultVO resultMockForTest(){
 return ResultVO(
 bestsellersDate: "2022-04-30",
 publishedDate: "2022-05-15",
 publishedDateDescription: "latest",
 previousPublishedDate: "2022-05-08",
 nextPublishedDate: "",
 lists:[
   BookListVO(
     listId: 704,
     listName: "Combined Print and E-Book Fiction",
     listNameEncoded: "combined-print-and-e-book-fiction",
     displayName: "Combined Print & E-Book Fiction",
     updated: "WEEKLY",
     listImage: null,
     listImageWidth: null,
     listImageHeight: null,
     books: [
       BookVO(
         numResults: 0,
         ageGroup: "",
         amazonProductUrl: "",
         articleChapterLink: "",
         author: "Colleen Hoover",
         bookImage: "https://storage.googleapis.com/du-prd/books/images/9781501110375.jpg",
         bookImageWidth: 319,
         bookImageHeight: 495,
         bookReviewLink: "",
         contributor: "by Colleen Hoover",
         contributorNote: "",
         createdDate: "2022-05-04 22:04:26",
         description: "A battered wife raised in a violent home attempts to halt the cycle of abuse.",
         firstChapterLink: "",
         price: "0.00",
         primaryIsbn10: "1501110365",
         primaryIsbn13: "9781501110368",
         bookUri: "nyt://book/e2a3545e-e9cb-5828-9d97-50a798a0e4f6",
         publisher: "Atria",
         rank: 1,
         rankLastWeek: 3,
         sundayReviewLink: "",
         title: "IT ENDS WITH US",
         updatedDate: "2022-05-04 22:09:03",
         weeksOnList: 46,
         buyLinks: [],
         categoryForOverView: "Combined Print and E-Book Fiction",
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger: null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         searchResult: null,
       ),

        BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: "",
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: 2,
         rankLastWeek: 1,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: 2,
         buyLinks: null,
         time: "0",
         listName: "Combined Print and E-Book Fiction",
         displayName: "Combined Print & E-Book Fiction",
         bestsellersDate: "2022-04-30",
         publishedDate: "2022-05-15",
         asterisk: 0,
         dagger: 0,
         isbns: [],
         bookDetails: [
           BookDetailsVO(
             title: "DREAM TOWN",
             description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
             contributor:  "by David Baldacci",
             author: "David Baldacci",
             contributorNote: "",
             price: "0.00",
             ageGroup: "",
             publisher: "Grand Central",
             primaryIsbn13: "9781538719770",
             primary_isbn10: "1538719770",
             time: "0",
           )
         ],
         categoryForOverView: null,
         reviews: [],
         searchResult: null,
       ),

       BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: null,
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: null,
         rankLastWeek: null,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: null,
         buyLinks: null,
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger:null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         categoryForOverView: null,
         searchResult: SearchResultVO(
           kind: "books#volume",
           id: "ex-tDwAAQBAJ",
           etag: "44HJbhwsKns",
           selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
           volumeInfo: VolumeInfoVO(
             title:  "Beginning Flutter",
             authors: ["Marco L. Napoli"],
             publisher: "John Wiley & Sons",
             publishedDate: "2019-10-08",
             description: "",
             industryIdentifiers: [],
             readingModes: ReadingModesVO(),
             pageCount: 528,
             printType: "BOOK",
             categories: ["Computers"],
             maturityRating: "NOT_MATURE",
             allowAnonLogging: false,
             contentVersion: "1.2.1.0.preview.1",
             panelizationSummary: PanelizationSummaryVO(),
             imageLinks: ImageLinksVO(
               thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
               smallThumbnail: "",
             ),
             language: "en",
             previewLink: "",
             infoLink: "",
             canonicalVolumeLink: "",
           ),
           saleInfo: SaleInfoVO(),
           accessInfo: AccessInfoVO(),
           searchInfo: SearchInfoVO(),
           ),
       ),
     ]
   )
  ],
 );
}


List<BookVO> showMoreMockForTest(){
  return  [
     BookVO(
          numResults: null,
         ageGroup: null,
         amazonProductUrl: "",
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: 2,
         rankLastWeek: 1,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: 2,
         buyLinks: null,
         time: "0",
         listName: "Combined Print and E-Book Fiction",
         displayName: "Combined Print & E-Book Fiction",
         bestsellersDate: "2022-04-30",
         publishedDate: "2022-05-15",
         asterisk: 0,
         dagger: 0,
         isbns: [],
         bookDetails: [
           BookDetailsVO(
             title: "DREAM TOWN",
             description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
             contributor:  "by David Baldacci",
             author: "David Baldacci",
             contributorNote: "",
             price: "0.00",
             ageGroup: "",
             publisher: "Grand Central",
             primaryIsbn13: "9781538719770",
             primary_isbn10: "1538719770",
             time: "0",
           )
         ],
         categoryForOverView: null,
         reviews: [],
         searchResult: null,
       ),
  ];
}

  ShowMoreListForHiveVO showMoreListForHiveMockForTest(){
    return ShowMoreListForHiveVO(
      bookList: [
        BookVO(
          numResults: null,
         ageGroup: null,
         amazonProductUrl: "",
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: 2,
         rankLastWeek: 1,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: 2,
         buyLinks: null,
         time: "0",
         listName: "Combined Print and E-Book Fiction",
         displayName: "Combined Print & E-Book Fiction",
         bestsellersDate: "2022-04-30",
         publishedDate: "2022-05-15",
         asterisk: 0,
         dagger: 0,
         isbns: [],
         bookDetails: [
           BookDetailsVO(
             title: "DREAM TOWN",
             description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
             contributor:  "by David Baldacci",
             author: "David Baldacci",
             contributorNote: "",
             price: "0.00",
             ageGroup: "",
             publisher: "Grand Central",
             primaryIsbn13: "9781538719770",
             primary_isbn10: "1538719770",
             time: "0",
           )
         ],
         categoryForOverView: null,
         reviews: [],
         searchResult: null,
       ),
      ],
    );
  }

List<SearchResultVO> searchResultVOMockForTest(){
  return [
    SearchResultVO(
           kind: "books#volume",
           id: "ex-tDwAAQBAJ",
           etag: "44HJbhwsKns",
           selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
           volumeInfo: VolumeInfoVO(
             title:  "Beginning Flutter",
             authors: ["Marco L. Napoli"],
             publisher: "John Wiley & Sons",
             publishedDate: "2019-10-08",
             description: "",
             industryIdentifiers: [],
             readingModes: ReadingModesVO(),
             pageCount: 528,
             printType: "BOOK",
             categories: ["Computers"],
             maturityRating: "NOT_MATURE",
             allowAnonLogging: false,
             contentVersion: "1.2.1.0.preview.1",
             panelizationSummary: PanelizationSummaryVO(),
             imageLinks: ImageLinksVO(
               thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
               smallThumbnail: "",
             ),
             language: "en",
             previewLink: "",
             infoLink: "",
             canonicalVolumeLink: "",
           ),
           saleInfo: SaleInfoVO(),
           accessInfo: AccessInfoVO(),
           searchInfo: SearchInfoVO(),
           ),
  ];
}

List<BookVO> bookListForCarouselMockForTest(){
  return [
       BookVO(
          numResults: 0,
         ageGroup: "",
         amazonProductUrl: "",
         articleChapterLink: "",
         author: "Colleen Hoover",
         bookImage: "https://storage.googleapis.com/du-prd/books/images/9781501110375.jpg",
         bookImageWidth: 319,
         bookImageHeight: 495,
         bookReviewLink: "",
         contributor: "by Colleen Hoover",
         contributorNote: "",
         createdDate: "2022-05-04 22:04:26",
         description: "A battered wife raised in a violent home attempts to halt the cycle of abuse.",
         firstChapterLink: "",
         price: "0.00",
         primaryIsbn10: "1501110365",
         primaryIsbn13: "9781501110368",
         bookUri: "nyt://book/e2a3545e-e9cb-5828-9d97-50a798a0e4f6",
         publisher: "Atria",
         rank: 1,
         rankLastWeek: 3,
         sundayReviewLink: "",
         title: "IT ENDS WITH US",
         updatedDate: "2022-05-04 22:09:03",
         weeksOnList: 46,
         buyLinks: [],
         categoryForOverView: "Combined Print and E-Book Fiction",
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger: null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         searchResult: null,
       ),

      //   BookVO(
      //     numResults: 0,
      //    ageGroup: null,
      //    amazonProductUrl: "",
      //    articleChapterLink: null,
      //    author: null,
      //    bookImage: null,
      //    bookImageWidth: null,
      //    bookImageHeight: null,
      //    bookReviewLink: null,
      //    contributor: null,
      //    contributorNote: null,
      //    createdDate: null,
      //    description: null,
      //    firstChapterLink: null,
      //    price:null,
      //    primaryIsbn10: null,
      //    primaryIsbn13: null,
      //    bookUri: null,
      //    publisher:null,
      //    rank: 2,
      //    rankLastWeek: 1,
      //    sundayReviewLink: null,
      //    title:null,
      //    updatedDate: null,
      //    weeksOnList: 2,
      //    buyLinks: null,
      //    time: "0",
      //    listName: "Combined Print and E-Book Fiction",
      //    displayName: "Combined Print & E-Book Fiction",
      //    bestsellersDate: "2022-04-30",
      //    publishedDate: "2022-05-15",
      //    asterisk: 0,
      //    dagger: 0,
      //    isbns: [],
      //    bookDetails: [
      //      BookDetailsVO(
      //        title: "DREAM TOWN",
      //        description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
      //        contributor:  "by David Baldacci",
      //        author: "David Baldacci",
      //        contributorNote: "",
      //        price: "0.00",
      //        ageGroup: "",
      //        publisher: "Grand Central",
      //        primaryIsbn13: "9781538719770",
      //        primary_isbn10: "1538719770",
      //        time: "0",
      //      )
      //    ],
      //    categoryForOverView: null,
      //    reviews: [],
      //    searchResult: null,
      //  ),

      //  BookVO(
      //     numResults: 0,
      //    ageGroup: null,
      //    amazonProductUrl: null,
      //    articleChapterLink: null,
      //    author: null,
      //    bookImage: null,
      //    bookImageWidth: null,
      //    bookImageHeight: null,
      //    bookReviewLink: null,
      //    contributor: null,
      //    contributorNote: null,
      //    createdDate: null,
      //    description: null,
      //    firstChapterLink: null,
      //    price:null,
      //    primaryIsbn10: null,
      //    primaryIsbn13: null,
      //    bookUri: null,
      //    publisher:null,
      //    rank: null,
      //    rankLastWeek: null,
      //    sundayReviewLink: null,
      //    title:null,
      //    updatedDate: null,
      //    weeksOnList: null,
      //    buyLinks: null,
      //    time: "0",
      //    listName: null,
      //    displayName: null,
      //    bestsellersDate: null,
      //    publishedDate: null,
      //    asterisk: null,
      //    dagger:null,
      //    isbns: null,
      //    bookDetails: null,
      //    reviews: null,
      //    categoryForOverView: null,
      //    searchResult: SearchResultVO(
      //      kind: "books#volume",
      //      id: "ex-tDwAAQBAJ",
      //      etag: "44HJbhwsKns",
      //      selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
      //      volumeInfo: VolumeInfoVO(
      //        title:  "Beginning Flutter",
      //        authors: ["Marco L. Napoli"],
      //        publisher: "John Wiley & Sons",
      //        publishedDate: "2019-10-08",
      //        description: "",
      //        industryIdentifiers: [],
      //        readingModes: ReadingModesVO(),
      //        pageCount: 528,
      //        printType: "BOOK",
      //        categories: ["Computers"],
      //        maturityRating: "NOT_MATURE",
      //        allowAnonLogging: false,
      //        contentVersion: "1.2.1.0.preview.1",
      //        panelizationSummary: PanelizationSummaryVO(),
      //        imageLinks: ImageLinksVO(
      //          thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      //          smallThumbnail: "",
      //        ),
      //        language: "en",
      //        previewLink: "",
      //        infoLink: "",
      //        canonicalVolumeLink: "",
      //      ),
      //      saleInfo: SaleInfoVO(),
      //      accessInfo: AccessInfoVO(),
      //      searchInfo: SearchInfoVO(),
      //      ),
      //  ),
  ];
}


List<ShelfVO> shelfListMockForTest(){
  return [
    ShelfVO(
      id: "2022-05-11 11:33:36.606",
      shelfName: "aaa",
      books: [
       BookVO(
          numResults: 0,
         ageGroup: "",
         amazonProductUrl: "",
         articleChapterLink: "",
         author: "Colleen Hoover",
         bookImage: "https://storage.googleapis.com/du-prd/books/images/9781501110375.jpg",
         bookImageWidth: 319,
         bookImageHeight: 495,
         bookReviewLink: "",
         contributor: "by Colleen Hoover",
         contributorNote: "",
         createdDate: "2022-05-04 22:04:26",
         description: "A battered wife raised in a violent home attempts to halt the cycle of abuse.",
         firstChapterLink: "",
         price: "0.00",
         primaryIsbn10: "1501110365",
         primaryIsbn13: "9781501110368",
         bookUri: "nyt://book/e2a3545e-e9cb-5828-9d97-50a798a0e4f6",
         publisher: "Atria",
         rank: 1,
         rankLastWeek: 3,
         sundayReviewLink: "",
         title: "IT ENDS WITH US",
         updatedDate: "2022-05-04 22:09:03",
         weeksOnList: 46,
         buyLinks: [],
         categoryForOverView: "Combined Print and E-Book Fiction",
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger: null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         searchResult: null,
       ),

        BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: "",
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: 2,
         rankLastWeek: 1,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: 2,
         buyLinks: null,
         time: "0",
         listName: "Combined Print and E-Book Fiction",
         displayName: "Combined Print & E-Book Fiction",
         bestsellersDate: "2022-04-30",
         publishedDate: "2022-05-15",
         asterisk: 0,
         dagger: 0,
         isbns: [],
         bookDetails: [
           BookDetailsVO(
             title: "DREAM TOWN",
             description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
             contributor:  "by David Baldacci",
             author: "David Baldacci",
             contributorNote: "",
             price: "0.00",
             ageGroup: "",
             publisher: "Grand Central",
             primaryIsbn13: "9781538719770",
             primary_isbn10: "1538719770",
             time: "0",
           )
         ],
         categoryForOverView: null,
         reviews: [],
         searchResult: null,
       ),

       BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: null,
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: null,
         rankLastWeek: null,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: null,
         buyLinks: null,
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger:null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         categoryForOverView: null,
         searchResult: SearchResultVO(
           kind: "books#volume",
           id: "ex-tDwAAQBAJ",
           etag: "44HJbhwsKns",
           selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
           volumeInfo: VolumeInfoVO(
             title:  "Beginning Flutter",
             authors: ["Marco L. Napoli"],
             publisher: "John Wiley & Sons",
             publishedDate: "2019-10-08",
             description: "",
             industryIdentifiers: [],
             readingModes: ReadingModesVO(),
             pageCount: 528,
             printType: "BOOK",
             categories: ["Computers"],
             maturityRating: "NOT_MATURE",
             allowAnonLogging: false,
             contentVersion: "1.2.1.0.preview.1",
             panelizationSummary: PanelizationSummaryVO(),
             imageLinks: ImageLinksVO(
               thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
               smallThumbnail: "",
             ),
             language: "en",
             previewLink: "",
             infoLink: "",
             canonicalVolumeLink: "",
           ),
           saleInfo: SaleInfoVO(),
           accessInfo: AccessInfoVO(),
           searchInfo: SearchInfoVO(),
           ),
       ),
  ],
    )
  ];
}


BookVO putBookToCarouselDatabase(){
  return BookVO(
          numResults: null,
         ageGroup: "",
         amazonProductUrl: "",
         articleChapterLink: "",
         author: "Colleen Hoover",
         bookImage: "https://storage.googleapis.com/du-prd/books/images/9781501110375.jpg",
         bookImageWidth: 319,
         bookImageHeight: 495,
         bookReviewLink: "",
         contributor: "by Colleen Hoover",
         contributorNote: "",
         createdDate: "2022-05-04 22:04:26",
         description: "A battered wife raised in a violent home attempts to halt the cycle of abuse.",
         firstChapterLink: "",
         price: "0.00",
         primaryIsbn10: "1501110365",
         primaryIsbn13: "9781501110368",
         bookUri: "nyt://book/e2a3545e-e9cb-5828-9d97-50a798a0e4f6",
         publisher: "Atria",
         rank: 1,
         rankLastWeek: 3,
         sundayReviewLink: "",
         title: "IT ENDS WITH US",
         updatedDate: "2022-05-04 22:09:03",
         weeksOnList: 46,
         buyLinks: [],
         categoryForOverView: "Combined Print and E-Book Fiction",
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger: null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         searchResult: null,
       );
}

ShelfVO createShelfToDatabase(){
  return ShelfVO(
      id: "2022-05-11 11:33:36.606",
      shelfName: "aaa",
      books: [
       BookVO(
          numResults: 0,
         ageGroup: "",
         amazonProductUrl: "",
         articleChapterLink: "",
         author: "Colleen Hoover",
         bookImage: "https://storage.googleapis.com/du-prd/books/images/9781501110375.jpg",
         bookImageWidth: 319,
         bookImageHeight: 495,
         bookReviewLink: "",
         contributor: "by Colleen Hoover",
         contributorNote: "",
         createdDate: "2022-05-04 22:04:26",
         description: "A battered wife raised in a violent home attempts to halt the cycle of abuse.",
         firstChapterLink: "",
         price: "0.00",
         primaryIsbn10: "1501110365",
         primaryIsbn13: "9781501110368",
         bookUri: "nyt://book/e2a3545e-e9cb-5828-9d97-50a798a0e4f6",
         publisher: "Atria",
         rank: 1,
         rankLastWeek: 3,
         sundayReviewLink: "",
         title: "IT ENDS WITH US",
         updatedDate: "2022-05-04 22:09:03",
         weeksOnList: 46,
         buyLinks: [],
         categoryForOverView: "Combined Print and E-Book Fiction",
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger: null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         searchResult: null,
       ),

        BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: "",
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: 2,
         rankLastWeek: 1,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: 2,
         buyLinks: null,
         time: "0",
         listName: "Combined Print and E-Book Fiction",
         displayName: "Combined Print & E-Book Fiction",
         bestsellersDate: "2022-04-30",
         publishedDate: "2022-05-15",
         asterisk: 0,
         dagger: 0,
         isbns: [],
         bookDetails: [
           BookDetailsVO(
             title: "DREAM TOWN",
             description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
             contributor:  "by David Baldacci",
             author: "David Baldacci",
             contributorNote: "",
             price: "0.00",
             ageGroup: "",
             publisher: "Grand Central",
             primaryIsbn13: "9781538719770",
             primary_isbn10: "1538719770",
             time: "0",
           )
         ],
         categoryForOverView: null,
         reviews: [],
         searchResult: null,
       ),

       BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: null,
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: null,
         rankLastWeek: null,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: null,
         buyLinks: null,
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger:null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         categoryForOverView: null,
         searchResult: SearchResultVO(
           kind: "books#volume",
           id: "ex-tDwAAQBAJ",
           etag: "44HJbhwsKns",
           selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
           volumeInfo: VolumeInfoVO(
             title:  "Beginning Flutter",
             authors: ["Marco L. Napoli"],
             publisher: "John Wiley & Sons",
             publishedDate: "2019-10-08",
             description: "",
             industryIdentifiers: [],
             readingModes: ReadingModesVO(),
             pageCount: 528,
             printType: "BOOK",
             categories: ["Computers"],
             maturityRating: "NOT_MATURE",
             allowAnonLogging: false,
             contentVersion: "1.2.1.0.preview.1",
             panelizationSummary: PanelizationSummaryVO(),
             imageLinks: ImageLinksVO(
               thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
               smallThumbnail: "",
             ),
             language: "en",
             previewLink: "",
             infoLink: "",
             canonicalVolumeLink: "",
           ),
           saleInfo: SaleInfoVO(),
           accessInfo: AccessInfoVO(),
           searchInfo: SearchInfoVO(),
           ),
       ),
  ],
    );
}


BookVO searBookMock(){
  return BookVO(
          numResults: null,
         ageGroup: null,
         amazonProductUrl: null,
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: null,
         rankLastWeek: null,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: null,
         buyLinks: null,
         time: null,
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger:null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         categoryForOverView: null,
         searchResult: SearchResultVO(
           kind: "books#volume",
           id: "ex-tDwAAQBAJ",
           etag: "44HJbhwsKns",
           selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
           volumeInfo: VolumeInfoVO(
             title:  "Beginning Flutter",
             authors: ["Marco L. Napoli"],
             publisher: "John Wiley & Sons",
             publishedDate: "2019-10-08",
             description: "",
             industryIdentifiers: [],
             readingModes: ReadingModesVO(),
             pageCount: 528,
             printType: "BOOK",
             categories: ["Computers"],
             maturityRating: "NOT_MATURE",
             allowAnonLogging: false,
             contentVersion: "1.2.1.0.preview.1",
             panelizationSummary: PanelizationSummaryVO(),
             imageLinks: ImageLinksVO(
               thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
               smallThumbnail: "",
             ),
             language: "en",
             previewLink: "",
             infoLink: "",
             canonicalVolumeLink: "",
           ),
           saleInfo: SaleInfoVO(),
           accessInfo: AccessInfoVO(),
           searchInfo: SearchInfoVO(),
           ),
       );
}


List<BookVO> bookListMock(){
  return [
       BookVO(
         numResults: 0,
         ageGroup: "",
         amazonProductUrl: "",
         articleChapterLink: "",
         author: "Colleen Hoover",
         bookImage: "https://storage.googleapis.com/du-prd/books/images/9781501110375.jpg",
         bookImageWidth: 319,
         bookImageHeight: 495,
         bookReviewLink: "",
         contributor: "by Colleen Hoover",
         contributorNote: "",
         createdDate: "2022-05-04 22:04:26",
         description: "A battered wife raised in a violent home attempts to halt the cycle of abuse.",
         firstChapterLink: "",
         price: "0.00",
         primaryIsbn10: "1501110365",
         primaryIsbn13: "9781501110368",
         bookUri: "nyt://book/e2a3545e-e9cb-5828-9d97-50a798a0e4f6",
         publisher: "Atria",
         rank: 1,
         rankLastWeek: 3,
         sundayReviewLink: "",
         title: "IT ENDS WITH US",
         updatedDate: "2022-05-04 22:09:03",
         weeksOnList: 46,
         buyLinks: [],
         categoryForOverView: "Combined Print and E-Book Fiction",
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger: null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         searchResult: null,
       ),

        BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: "",
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: 2,
         rankLastWeek: 1,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: 2,
         buyLinks: null,
         time: "0",
         listName: "Combined Print and E-Book Fiction",
         displayName: "Combined Print & E-Book Fiction",
         bestsellersDate: "2022-04-30",
         publishedDate: "2022-05-15",
         asterisk: 0,
         dagger: 0,
         isbns: [],
         bookDetails: [
           BookDetailsVO(
             title: "DREAM TOWN",
             description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
             contributor:  "by David Baldacci",
             author: "David Baldacci",
             contributorNote: "",
             price: "0.00",
             ageGroup: "",
             publisher: "Grand Central",
             primaryIsbn13: "9781538719770",
             primary_isbn10: "1538719770",
             time: "0",
           )
         ],
         categoryForOverView: null,
         reviews: [],
         searchResult: null,
       ),

       BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: null,
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: null,
         rankLastWeek: null,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: null,
         buyLinks: null,
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger:null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         categoryForOverView: null,
         searchResult: SearchResultVO(
           kind: "books#volume",
           id: "ex-tDwAAQBAJ",
           etag: "44HJbhwsKns",
           selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
           volumeInfo: VolumeInfoVO(
             title:  "Beginning Flutter",
             authors: ["Marco L. Napoli"],
             publisher: "John Wiley & Sons",
             publishedDate: "2019-10-08",
             description: "",
             industryIdentifiers: [],
             readingModes: ReadingModesVO(),
             pageCount: 528,
             printType: "BOOK",
             categories: ["Computers"],
             maturityRating: "NOT_MATURE",
             allowAnonLogging: false,
             contentVersion: "1.2.1.0.preview.1",
             panelizationSummary: PanelizationSummaryVO(),
             imageLinks: ImageLinksVO(
               thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
               smallThumbnail: "",
             ),
             language: "en",
             previewLink: "",
             infoLink: "",
             canonicalVolumeLink: "",
           ),
           saleInfo: SaleInfoVO(),
           accessInfo: AccessInfoVO(),
           searchInfo: SearchInfoVO(),
           ),
       ),
     ];
}

List<BookListVO> bookListTitleAndSerialMock(){
  return [
   BookListVO(
     listId: 704,
     listName: "Combined Print and E-Book Fiction",
     listNameEncoded: "combined-print-and-e-book-fiction",
     displayName: "Combined Print & E-Book Fiction",
     updated: "WEEKLY",
     listImage: null,
     listImageWidth: null,
     listImageHeight: null,
     books: [
       BookVO(
         numResults: 0,
         ageGroup: "",
         amazonProductUrl: "",
         articleChapterLink: "",
         author: "Colleen Hoover",
         bookImage: "https://storage.googleapis.com/du-prd/books/images/9781501110375.jpg",
         bookImageWidth: 319,
         bookImageHeight: 495,
         bookReviewLink: "",
         contributor: "by Colleen Hoover",
         contributorNote: "",
         createdDate: "2022-05-04 22:04:26",
         description: "A battered wife raised in a violent home attempts to halt the cycle of abuse.",
         firstChapterLink: "",
         price: "0.00",
         primaryIsbn10: "1501110365",
         primaryIsbn13: "9781501110368",
         bookUri: "nyt://book/e2a3545e-e9cb-5828-9d97-50a798a0e4f6",
         publisher: "Atria",
         rank: 1,
         rankLastWeek: 3,
         sundayReviewLink: "",
         title: "IT ENDS WITH US",
         updatedDate: "2022-05-04 22:09:03",
         weeksOnList: 46,
         buyLinks: [],
         categoryForOverView: "Combined Print and E-Book Fiction",
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger: null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         searchResult: null,
       ),

        BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: "",
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: 2,
         rankLastWeek: 1,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: 2,
         buyLinks: null,
         time: "0",
         listName: "Combined Print and E-Book Fiction",
         displayName: "Combined Print & E-Book Fiction",
         bestsellersDate: "2022-04-30",
         publishedDate: "2022-05-15",
         asterisk: 0,
         dagger: 0,
         isbns: [],
         bookDetails: [
           BookDetailsVO(
             title: "DREAM TOWN",
             description: "The third book in the Archer series. Archer, Dash and Callahan search for a missing screenwriter who had a dead body turn up in her home.",
             contributor:  "by David Baldacci",
             author: "David Baldacci",
             contributorNote: "",
             price: "0.00",
             ageGroup: "",
             publisher: "Grand Central",
             primaryIsbn13: "9781538719770",
             primary_isbn10: "1538719770",
             time: "0",
           )
         ],
         categoryForOverView: null,
         reviews: [],
         searchResult: null,
       ),

       BookVO(
          numResults: 0,
         ageGroup: null,
         amazonProductUrl: null,
         articleChapterLink: null,
         author: null,
         bookImage: null,
         bookImageWidth: null,
         bookImageHeight: null,
         bookReviewLink: null,
         contributor: null,
         contributorNote: null,
         createdDate: null,
         description: null,
         firstChapterLink: null,
         price:null,
         primaryIsbn10: null,
         primaryIsbn13: null,
         bookUri: null,
         publisher:null,
         rank: null,
         rankLastWeek: null,
         sundayReviewLink: null,
         title:null,
         updatedDate: null,
         weeksOnList: null,
         buyLinks: null,
         time: "0",
         listName: null,
         displayName: null,
         bestsellersDate: null,
         publishedDate: null,
         asterisk: null,
         dagger:null,
         isbns: null,
         bookDetails: null,
         reviews: null,
         categoryForOverView: null,
         searchResult: SearchResultVO(
           kind: "books#volume",
           id: "ex-tDwAAQBAJ",
           etag: "44HJbhwsKns",
           selfLink: "https://www.googleapis.com/books/v1/volumes/ex-tDwAAQBAJ",
           volumeInfo: VolumeInfoVO(
             title:  "Beginning Flutter",
             authors: ["Marco L. Napoli"],
             publisher: "John Wiley & Sons",
             publishedDate: "2019-10-08",
             description: "",
             industryIdentifiers: [],
             readingModes: ReadingModesVO(),
             pageCount: 528,
             printType: "BOOK",
             categories: ["Computers"],
             maturityRating: "NOT_MATURE",
             allowAnonLogging: false,
             contentVersion: "1.2.1.0.preview.1",
             panelizationSummary: PanelizationSummaryVO(),
             imageLinks: ImageLinksVO(
               thumbnail: "http://books.google.com/books/content?id=ex-tDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
               smallThumbnail: "",
             ),
             language: "en",
             previewLink: "",
             infoLink: "",
             canonicalVolumeLink: "",
           ),
           saleInfo: SaleInfoVO(),
           accessInfo: AccessInfoVO(),
           searchInfo: SearchInfoVO(),
           ),
       ),
     ]
   )
  ];
}


